name: OreAbilities
version: 1.0.0
main: hs.orePlugin.OreAbilitiesPlugin
api-version: 1.21
author: YourName
description: A plugin that gives players special abilities based on ore types

commands:
  trust:
    description: Trust a player to prevent friendly fire
    usage: /trust <player>
    permission: oreabilities.trust
  untrust:
    description: Remove trust from a player
    usage: /untrust <player>
    permission: oreabilities.trust
  trustlist:
    description: List all trusted players
    usage: /trustlist
    permission: oreabilities.trust
  oreabilities:
    description: Main ore abilities command
    usage: /oreabilities [info|help|reload|reset]
    permission: oreabilities.use
    aliases: [oa, ore]

permissions:
  oreabilities.*:
    description: All ore abilities permissions
    children:
      oreabilities.use: true
      oreabilities.trust: true
      oreabilities.admin: true
  oreabilities.use:
    description: Use ore abilities
    default: true
  oreabilities.trust:
    description: Use trust commands
    default: true
  oreabilities.admin:
    description: Admin commands
    default: op