name: OreAbilities
version: 1.0.0
main: hs.orePlugin.OreAbilitiesPlugin
api-version: 1.21
author: '___Pumpkinn'
description: A plugin that gives players special abilities based on ore types

commands:
  trust:
    description: Trust a player to prevent friendly fire
    usage: /trust <player>
    permission: oreabilities.trust
  untrust:
    description: Remove trust from a player
    usage: /untrust <player>
    permission: oreabilities.trust
  trustlist:
    description: List all trusted players
    usage: /trustlist
    permission: oreabilities.trust
  oreabilities:
    description: Main ore abilities command with detailed ore information
    usage: /oreabilities [info|oreinfo|help|set|bedrock|ability|reload|reset]
    permission: oreabilities.use
    aliases: [oa, ore, oreinfo]
  ability:
    description: Activate your ore ability (Bedrock Edition support)
    usage: /ability
    permission: oreabilities.use
  bedrock:
    description: Toggle Bedrock Edition mode for ability activation
    usage: /bedrock
    permission: oreabilities.use

permissions:
  oreabilities.*:
    description: All ore abilities permissions
    children:
      oreabilities.use: true
      oreabilities.trust: true
      oreabilities.admin: true
  oreabilities.use:
    description: Use ore abilities
    default: true
  oreabilities.trust:
    description: Use trust commands
    default: true
  oreabilities.admin:
    description: Admin commands (set ore types, reset, reload)
    default: op