name: OreAbilities
version: 1.0.0
main: hs.orePlugin.OreAbilitiesPlugin
api-version: 1.21
author: '___Pumpkinn'
load: STARTUP
description: A plugin that gives players special abilities based on ore types

commands:
  trust:
    description: Trust a player to prevent friendly fire
    usage: /trust <player>
    permission: oreabilities.trust
  untrust:
    description: Remove trust from a player
    usage: /untrust <player>
    permission: oreabilities.trust
  trustlist:
    description: List all trusted players
    usage: /trustlist
    permission: oreabilities.trust
  ore:
    description: Main ore command - simplified and easy to use
    usage: /ore [info|list|help|change|reset|recipes|<orename>]
    permission: oreabilities.use
    aliases: [oreabilities, oa]
  ability:
    description: Activate your ore ability (Bedrock Edition support)
    usage: /ability
    permission: oreabilities.use
  bedrock:
    description: Toggle Bedrock Edition mode for ability activation
    usage: /bedrock
    permission: oreabilities.use
  orecd:
    description: Reset ore ability cooldown (Admin only)
    usage: /orecd reset [player]
    permission: oreabilities.admin
  recipes:
    description: View ore crafting recipes in a GUI
    usage: /recipes [ore]
    permission: oreabilities.use
    aliases: [recipe, orerecipes]

permissions:
  oreabilities.*:
    description: All ore abilities permissions
    default: op
    children:
      oreabilities.use: true
      oreabilities.trust: true
      oreabilities.admin: true
  oreabilities.use:
    description: Basic ore abilities usage
    default: true
  oreabilities.trust:
    description: Use trust system
    default: true
  oreabilities.admin:
    description: Admin commands for ore abilities
    default: op