# Ore Abilities Plugin Configuration

# Plugin Settings
plugin:
  # Enable debug messages
  debug: false

  # Auto-save interval (in minutes)
  auto-save-interval: 5

# Ore Settings
ores:
  # Chance for ore to shatter when crafting (0.0 - 1.0)
  shatter-chance: 0.25

  # Enable/disable specific ore types
  enabled-ores:
    dirt: true
    wood: true
    stone: true
    coal: true
    copper: true
    iron: true
    gold: true
    redstone: true
    lapis: true
    emerald: true
    amethyst: true
    diamond: true
    netherite: true

# Ability Cooldowns (in seconds) - can be overridden here
cooldowns:
  dirt: 30
  wood: 30
  stone: 30
  coal: 10
  copper: 45
  iron: 45
  gold: 120  # Updated from 75 to 120 seconds
  redstone: 80
  lapis: 240
  emerald: 270
  amethyst: 120
  diamond: 360
  netherite: 600

# Trust System Settings
trust:
  # Maximum number of trusted players per player
  max-trusted-players: 10

  # Trust request timeout (in seconds)
  request-timeout: 60

  # Enable trust notifications
  enable-notifications: true

# Effects Settings
effects:
  # Iron ore item drop interval (in minutes)
  iron-drop-interval: 10

  # Enable particle effects
  enable-particles: true

  # Enable sound effects
  enable-sounds: true

  # Action bar settings
  action-bar:
    # Enable action bar display
    enabled: true

    # Update interval in ticks (20 = 1 second)
    update-interval: 20

    # Show progress bar for cooldowns
    show-progress-bar: true

# Copper Ore Settings
copper:
  # Armor durability multiplier (how much faster armor breaks)
  armor-durability-multiplier: 2.0

  # How often to check and damage armor (in ticks, 20 = 1 second)
  armor-damage-interval: 100

# Coal Ore Settings
coal:
  # Water damage amount per tick
  water-damage: 2.0

  # Damage interval while in water (in milliseconds)
  water-damage-interval: 2000

# Messages (can be customized) - FIXED: Proper color code format
messages:
  no-permission: "&cYou don't have permission to use this command!"
  player-not-found: "&cPlayer not found or not online!"
  ability-on-cooldown: "&cAbility on cooldown! {time} seconds remaining."
  ability-ready: "&aAbility ready! Right-click to use."
  ore-assigned: "&6You have been assigned the {ore} ore type!"
  ore-shattered: "&cThe ore shattered during crafting!"
  coal-water-damage: "&8Coal curse! Water burns you!"
  copper-lightning-protection: "&3Copper protection from lightning!"
  redstone-jump-prevent: "&4You cannot jump for 10 seconds!"
  amethyst-crystal-mode: "&dCrystal mode activated - No damage or knockback!"
  gold-durability-curse: "&6Gold curse! Item durability randomized!"
  emerald-weakness-warning: "&cEmerald curse! You need at least 4 stacks of emeralds!"
  emerald-weakness-removed: "&aEmerald blessing! Weakness removed!"
  diamond-ore-prevented: "&cDiamond curse prevented ore drop!"
  netherite-ancient-debris: "&4Netherite blessing! Ancient debris became netherite ingot!"
  lapis-anvil-blessing: "&9Lapis blessing! No levels required for anvil use!"
  lapis-levels-restored: "&9Lapis blessing! Your levels have been restored!"
  lapis-villager-blocked: "&cLapis prevents you from trading with villagers!"
  no-ore-type: "&cYou don't have an ore type assigned!"